### ISSUE TITLE
policyのモデル重みをkeras -> Chainerに変換

### ISSUE THREAD

**Issue by milhidaka** [lerrytang/learning_to_run#3]
Kerasのh5ファイルを読み込んでChainerのnpzファイルにする

**Comment by fukuta0614** [comment]
self.log_std = chainer.Parameter(shape=(self.action_dim,), initializer=chainer.initializers.Zero())
ついでにこいつもnpzにくっつけておいてくれると嬉しいです。

**Comment by fukuta0614** [comment]
一応伝えておくと、、こちらのlayerの名前、["fc1", "fc2", ..., "l_act"]って感じです。

**Comment by milhidaka** [comment]
@fukuta0614 hidaka/trpo-convert ブランチの dev/convert_keras_chainer.py に置いたので試して見てください。先日のcandidate_01.zipを解凍してtrialsの下においてください。

**Comment by fukuta0614** [comment]
神です。動きました。
再現できました。
